version: "3.3"
services:

  token-flow-service:
    volumes:
      - ./web/service:/app
      - ./web/contexts:/app/contexts
      - ./src:/app/src
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - INSTALL_DEV=true
    ports:
      - "8081:80"
    command: [ "/start-reload.sh" ]
    # command: [ "/app/start.sh" ]
    networks:
      - token-flow-net

  token-flow-web:
    build:
      context: ./web/ui
    ports:
      - 8080:3000
    volumes:
      - ./web/ui:/app
    environment:
      - NODE_ENV=development
      - SKIP_PREFLIGHT_CHECK=true
    stdin_open: true

volumes:
  store-data-volume: null

networks:
  token-flow-net:
